[project]
name = "mtg-tagger"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.9"
dependencies = [
    "anthropic>=0.79.0",
    "flask>=3.1.2",
]

[dependency-groups]
dev = [
    "pytest>=8.4.2",
]
